[2023-10-15 01:15:49,349: INFO: main: Welcome to our custom log]
[2023-10-15 01:26:36,265: INFO: main: Welcome to our custom log]
[2023-10-15 11:27:53,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 11:27:53,619: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 11:27:53,621: INFO: common: Created directory at: artifacts]
[2023-10-15 11:27:53,623: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 11:27:53,625: INFO: 3812226400: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data/ingestion/data.zip]
[2023-10-15 11:29:32,502: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 11:29:32,504: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 11:29:32,505: INFO: common: Created directory at: artifacts]
[2023-10-15 11:29:32,506: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 11:29:32,507: INFO: 3812226400: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-15 11:29:38,785: INFO: 3812226400: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-15 11:42:50,533: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-15 11:42:50,534: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 11:42:50,535: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 11:42:50,535: INFO: common: Created directory at: artifacts]
[2023-10-15 11:42:50,536: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 11:42:50,537: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-15 11:42:57,575: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-15 11:42:58,403: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-15 12:31:32,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:31:32,342: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:31:32,344: INFO: common: Created directory at: artifacts]
[2023-10-15 12:32:09,665: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:32:09,668: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:32:09,669: INFO: common: Created directory at: artifacts]
[2023-10-15 12:32:09,670: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 12:33:39,812: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:33:39,815: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:33:39,816: INFO: common: Created directory at: artifacts]
[2023-10-15 12:33:39,817: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 12:34:05,470: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:34:05,478: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:34:05,480: INFO: common: Created directory at: artifacts]
[2023-10-15 12:34:05,481: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 12:34:55,904: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:34:55,906: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:34:55,908: INFO: common: Created directory at: artifacts]
[2023-10-15 12:34:55,909: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 12:35:02,467: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 12:35:29,226: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:35:29,230: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:35:29,232: INFO: common: Created directory at: artifacts]
[2023-10-15 12:35:29,234: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 12:35:29,652: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 12:49:01,873: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-15 12:49:01,875: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:49:01,876: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:49:01,876: INFO: common: Created directory at: artifacts]
[2023-10-15 12:49:01,877: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 12:49:01,877: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-15 12:49:08,889: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-15 12:49:09,612: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-15 12:49:09,612: INFO: main: *************************]
[2023-10-15 12:49:09,612: INFO: main: >>>>>> Stage Prepare Base Model started <<<<<<]
[2023-10-15 12:49:09,613: ERROR: main: main() takes 0 positional arguments but 1 was given]
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    obj.main()
TypeError: main() takes 0 positional arguments but 1 was given
[2023-10-15 12:53:19,838: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-15 12:53:19,840: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:53:19,842: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:53:19,843: INFO: common: Created directory at: artifacts]
[2023-10-15 12:53:19,843: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 12:53:19,844: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-15 12:53:26,019: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-15 12:53:26,666: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-15 12:53:26,666: INFO: main: *************************]
[2023-10-15 12:53:26,666: INFO: main: >>>>>> Stage Prepare Base Model started <<<<<<]
[2023-10-15 12:53:26,668: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 12:53:26,669: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 12:53:26,670: INFO: common: Created directory at: artifacts]
[2023-10-15 12:53:26,670: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 12:53:27,053: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 12:53:27,248: INFO: main: >>>>>>> Stage Prepare Base Model completed <<<<<<<

x===================x]
[2023-10-15 13:29:00,430: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:29:00,433: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:29:00,434: INFO: common: Created directory at: artifacts]
[2023-10-15 13:29:00,435: INFO: common: Created directory at: artifacts\training]
[2023-10-15 13:29:59,074: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:29:59,078: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:29:59,080: INFO: common: Created directory at: artifacts]
[2023-10-15 13:29:59,081: INFO: common: Created directory at: artifacts\training]
[2023-10-15 13:34:38,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:34:38,811: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:34:38,813: INFO: common: Created directory at: artifacts]
[2023-10-15 13:34:38,815: INFO: common: Created directory at: artifacts\training]
[2023-10-15 13:36:13,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:36:13,154: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:36:13,156: INFO: common: Created directory at: artifacts]
[2023-10-15 13:36:13,157: INFO: common: Created directory at: artifacts\training]
[2023-10-15 13:37:08,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:37:08,824: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:37:08,825: INFO: common: Created directory at: artifacts]
[2023-10-15 13:37:08,827: INFO: common: Created directory at: artifacts\training]
[2023-10-15 13:52:59,234: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-15 13:52:59,236: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:52:59,237: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:52:59,238: INFO: common: Created directory at: artifacts]
[2023-10-15 13:52:59,238: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 13:52:59,239: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-15 13:53:06,340: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-15 13:53:07,072: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-15 13:53:07,073: INFO: main: *************************]
[2023-10-15 13:53:07,073: INFO: main: >>>>>> Stage Prepare Base Model started <<<<<<]
[2023-10-15 13:53:07,076: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:53:07,078: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:53:07,078: INFO: common: Created directory at: artifacts]
[2023-10-15 13:53:07,080: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 13:53:07,637: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 13:53:07,940: INFO: main: >>>>>>> Stage Prepare Base Model completed <<<<<<<

x===================x]
[2023-10-15 13:53:07,942: INFO: main: *************************]
[2023-10-15 13:53:07,942: INFO: main: >>>>>> Stage Training started <<<<<<]
[2023-10-15 13:53:07,944: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:53:07,947: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:53:07,948: INFO: common: Created directory at: artifacts]
[2023-10-15 13:53:07,949: INFO: common: Created directory at: artifacts\training]
[2023-10-15 13:53:08,475: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    model_trainer.main()
  File "c:\users\rajat\onedrive\desktop\projects\kidney-disease-classification-mlflow\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_genarator()
  File "c:\users\rajat\onedrive\desktop\projects\kidney-disease-classification-mlflow\src\cnnClassifier\components\model_training.py", line 38, in train_valid_genarator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2023-10-15 13:58:14,829: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-15 13:58:14,836: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:58:14,837: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:58:14,838: INFO: common: Created directory at: artifacts]
[2023-10-15 13:58:14,838: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 13:58:14,839: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/kid.zip]
[2023-10-15 13:58:38,393: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-15 13:58:38,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:58:38,397: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:58:38,398: INFO: common: Created directory at: artifacts]
[2023-10-15 13:58:38,398: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 13:58:38,399: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/kid.zip]
[2023-10-15 13:58:45,283: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/kid.zip]
[2023-10-15 13:58:45,939: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-15 13:58:45,940: INFO: main: *************************]
[2023-10-15 13:58:45,940: INFO: main: >>>>>> Stage Prepare Base Model started <<<<<<]
[2023-10-15 13:58:45,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:58:45,944: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:58:45,945: INFO: common: Created directory at: artifacts]
[2023-10-15 13:58:45,945: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 13:58:46,425: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 13:58:46,687: INFO: main: >>>>>>> Stage Prepare Base Model completed <<<<<<<

x===================x]
[2023-10-15 13:58:46,687: INFO: main: *************************]
[2023-10-15 13:58:46,687: INFO: main: >>>>>> Stage Training started <<<<<<]
[2023-10-15 13:58:46,690: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 13:58:46,692: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 13:58:46,693: INFO: common: Created directory at: artifacts]
[2023-10-15 13:58:46,694: INFO: common: Created directory at: artifacts\training]
[2023-10-15 13:58:47,217: ERROR: main: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image']
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    model_trainer.main()
  File "c:\users\rajat\onedrive\desktop\projects\kidney-disease-classification-mlflow\src\cnnClassifier\pipeline\stage_03_model_training.py", line 18, in main
    training.train_valid_genarator()
  File "c:\users\rajat\onedrive\desktop\projects\kidney-disease-classification-mlflow\src\cnnClassifier\components\model_training.py", line 38, in train_valid_genarator
    self.valid_generator = valid_datagenerator.flow_from_directory(
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 1648, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\keras\preprocessing\image.py", line 563, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\kidney-ct-scan-image'
[2023-10-15 14:02:31,122: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 14:02:31,126: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 14:02:31,128: INFO: common: Created directory at: artifacts]
[2023-10-15 14:02:31,130: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 14:02:31,133: INFO: 3102992666: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-15 14:02:38,167: INFO: 3102992666: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-15 14:13:32,254: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-15 14:13:32,258: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 14:13:32,260: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 14:13:32,262: INFO: common: Created directory at: artifacts]
[2023-10-15 14:13:32,263: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-15 14:13:32,265: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-15 14:13:39,339: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-15 14:13:40,032: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-15 14:13:40,032: INFO: main: *************************]
[2023-10-15 14:13:40,032: INFO: main: >>>>>> Stage Prepare Base Model started <<<<<<]
[2023-10-15 14:13:40,035: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 14:13:40,037: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 14:13:40,037: INFO: common: Created directory at: artifacts]
[2023-10-15 14:13:40,038: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-15 14:13:40,451: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-15 14:13:40,647: INFO: main: >>>>>>> Stage Prepare Base Model completed <<<<<<<

x===================x]
[2023-10-15 14:13:40,647: INFO: main: *************************]
[2023-10-15 14:13:40,647: INFO: main: >>>>>> Stage Training started <<<<<<]
[2023-10-15 14:13:40,649: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-15 14:13:40,651: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-15 14:13:40,651: INFO: common: Created directory at: artifacts]
[2023-10-15 14:13:40,652: INFO: common: Created directory at: artifacts\training]
[2023-10-15 14:15:29,346: INFO: main: >>>>>>> Stage Training completed <<<<<<<

x===================x]
[2023-10-21 23:13:45,775: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:13:45,782: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:13:45,783: INFO: common: Created directory at: artifacts]
[2023-10-21 23:14:33,660: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:14:33,663: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:14:33,665: INFO: common: Created directory at: artifacts]
[2023-10-21 23:18:14,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:18:14,956: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:18:14,957: INFO: common: Created directory at: artifacts]
[2023-10-21 23:19:20,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:19:20,097: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:19:20,099: INFO: common: Created directory at: artifacts]
[2023-10-21 23:20:06,925: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:20:06,928: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:20:06,930: INFO: common: Created directory at: artifacts]
[2023-10-21 23:21:01,266: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:21:01,269: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:21:01,270: INFO: common: Created directory at: artifacts]
[2023-10-21 23:21:50,355: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:21:50,358: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:21:50,361: INFO: common: Created directory at: artifacts]
[2023-10-21 23:22:24,974: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-10-21 23:22:25,773: INFO: builder_impl: Assets written to: C:\Users\rajat\AppData\Local\Temp\tmpv__rxca1\model\data\model\assets]
[2023-10-21 23:33:49,721: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:33:49,726: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:33:49,727: INFO: common: Created directory at: artifacts]
[2023-10-21 23:40:46,562: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:40:46,565: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:40:46,567: INFO: common: Created directory at: artifacts]
[2023-10-21 23:46:12,159: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:46:12,164: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:46:12,168: INFO: common: Created directory at: artifacts]
[2023-10-21 23:47:19,560: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:47:19,562: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:47:19,564: INFO: common: Created directory at: artifacts]
[2023-10-21 23:48:30,844: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-21 23:48:30,848: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-21 23:48:30,851: INFO: common: Created directory at: artifacts]
[2023-10-21 23:48:51,536: INFO: common: Json file saved successfully at: scores.json]
[2023-10-21 23:48:57,080: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-10-21 23:48:57,790: INFO: builder_impl: Assets written to: C:\Users\rajat\AppData\Local\Temp\tmpfjjiev7r\model\data\model\assets]
[2023-10-21 23:50:07,426: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)': /RG-Le/Kidney-Disease-Classification-MLFlow.mlflow/api/2.0/mlflow-artifacts/artifacts/791ce489aa9a4c828ece33a05f25dfff/ab984979d83a4f249528df78e9936447/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2023-10-22 00:05:07,883: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-22 00:05:07,886: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-22 00:05:07,893: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-22 00:05:07,893: INFO: common: Created directory at: artifacts]
[2023-10-22 00:05:07,894: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-22 00:05:07,894: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-22 00:05:14,437: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-22 00:05:15,208: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-22 00:05:15,208: INFO: main: *************************]
[2023-10-22 00:05:15,208: INFO: main: >>>>>> Stage Prepare Base Model started <<<<<<]
[2023-10-22 00:05:15,210: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-22 00:05:15,212: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-22 00:05:15,212: INFO: common: Created directory at: artifacts]
[2023-10-22 00:05:15,213: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-22 00:05:15,754: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-22 00:05:15,992: INFO: main: >>>>>>> Stage Prepare Base Model completed <<<<<<<

x===================x]
[2023-10-22 00:05:15,992: INFO: main: *************************]
[2023-10-22 00:05:15,992: INFO: main: >>>>>> Stage Training started <<<<<<]
[2023-10-22 00:05:15,995: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-22 00:05:15,997: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-22 00:05:15,997: INFO: common: Created directory at: artifacts]
[2023-10-22 00:05:15,998: INFO: common: Created directory at: artifacts\training]
[2023-10-22 00:07:16,885: INFO: main: >>>>>>> Stage Training completed <<<<<<<

x===================x]
[2023-10-22 00:07:16,885: INFO: main: *************************]
[2023-10-22 00:07:16,885: INFO: main: >>>>>> Stage Model Evaluation started <<<<<<]
[2023-10-22 00:07:16,888: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-22 00:07:16,890: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-22 00:07:16,890: INFO: common: Created directory at: artifacts]
[2023-10-22 00:07:34,719: INFO: common: Json file saved successfully at: scores.json]
[2023-10-22 00:07:40,369: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-10-22 00:07:40,976: INFO: builder_impl: Assets written to: C:\Users\rajat\AppData\Local\Temp\tmpn0rrjhi2\model\data\model\assets]
[2023-10-22 00:08:58,758: INFO: main: >>>>>>> Stage Model Evaluation completed <<<<<<<

x===================x]
[2023-10-22 00:10:44,210: INFO: main: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-22 00:10:44,213: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-22 00:10:44,219: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-22 00:10:44,220: INFO: common: Created directory at: artifacts]
[2023-10-22 00:10:44,221: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-22 00:10:44,221: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-22 00:10:51,402: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-22 00:10:52,061: INFO: main: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-22 00:10:52,061: INFO: main: *************************]
[2023-10-22 00:10:52,062: INFO: main: >>>>>> Stage Prepare Base Model started <<<<<<]
[2023-10-22 00:10:52,064: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-22 00:10:52,065: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-22 00:10:52,065: INFO: common: Created directory at: artifacts]
[2023-10-22 00:10:52,066: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-22 00:10:52,493: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-22 00:10:52,721: INFO: main: >>>>>>> Stage Prepare Base Model completed <<<<<<<

x===================x]
[2023-10-22 00:10:52,721: INFO: main: *************************]
[2023-10-22 00:10:52,721: INFO: main: >>>>>> Stage Training started <<<<<<]
[2023-10-22 00:10:52,724: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-22 00:10:52,726: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-22 00:10:52,727: INFO: common: Created directory at: artifacts]
[2023-10-22 00:10:52,727: INFO: common: Created directory at: artifacts\training]
[2023-10-22 00:12:56,089: INFO: main: >>>>>>> Stage Training completed <<<<<<<

x===================x]
[2023-10-22 00:12:56,090: INFO: main: *************************]
[2023-10-22 00:12:56,090: INFO: main: >>>>>> Stage Model Evaluation started <<<<<<]
[2023-10-22 00:12:56,092: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-22 00:12:56,094: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-22 00:12:56,094: INFO: common: Created directory at: artifacts]
[2023-10-22 00:13:15,988: INFO: common: Json file saved successfully at: scores.json]
[2023-10-22 00:13:36,350: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/log-batch failed with error code 400 != 200. Response body: '"repo not associated with run"']
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    model_trainer.main()
  File "c:\users\rajat\onedrive\desktop\projects\kidney-disease-classification-mlflow\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\rajat\onedrive\desktop\projects\kidney-disease-classification-mlflow\src\cnnClassifier\components\model_evaluation_mlflow.py", line 62, in log_into_mlflow
    mlflow.log_metrics(
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\fluent.py", line 677, in log_metrics
    MlflowClient().log_batch(run_id=run_id, metrics=metrics_arr, params=[], tags=[])
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 986, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 394, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics_batch, params=[], tags=[])
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 321, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\mlflow\store\tracking\rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/log-batch failed with error code 400 != 200. Response body: '"repo not associated with run"'
[2023-10-25 23:29:44,174: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage started <<<<<<<]
[2023-10-25 23:29:44,177: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-25 23:29:44,180: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-25 23:29:44,181: INFO: common: Created directory at: artifacts]
[2023-10-25 23:29:44,182: INFO: common: Created directory at: artifacts/data_ingestion]
[2023-10-25 23:29:44,182: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing intp file artifacts/data_ingestion/data.zip]
[2023-10-25 23:29:51,508: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1lQSleJtjX222_GugfMKaJPWYJ5zmB0qD/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-10-25 23:29:52,346: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion Stage completed <<<<<<

x===========x]
[2023-10-25 23:30:08,866: INFO: stage_02_prepare_base_model: *************************]
[2023-10-25 23:30:08,866: INFO: stage_02_prepare_base_model: >>>>>> Stage Prepare Base Model started <<<<<<]
[2023-10-25 23:30:08,868: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-25 23:30:08,870: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-25 23:30:08,871: INFO: common: Created directory at: artifacts]
[2023-10-25 23:30:08,871: INFO: common: Created directory at: artifacts/prepare_base_model]
[2023-10-25 23:30:09,446: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-10-25 23:30:09,673: INFO: stage_02_prepare_base_model: >>>>>>> Stage Prepare Base Model completed <<<<<<<

x===================x]
[2023-10-25 23:30:16,205: INFO: stage_03_model_training: *************************]
[2023-10-25 23:30:16,205: INFO: stage_03_model_training: >>>>>> Stage Training started <<<<<<]
[2023-10-25 23:30:16,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-25 23:30:16,210: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-25 23:30:16,210: INFO: common: Created directory at: artifacts]
[2023-10-25 23:30:16,211: INFO: common: Created directory at: artifacts\training]
[2023-10-25 23:32:34,950: INFO: stage_03_model_training: >>>>>>> Stage Training completed <<<<<<<

x===================x]
[2023-10-25 23:32:43,688: INFO: stage_04_model_evaluation: *************************]
[2023-10-25 23:32:43,689: INFO: stage_04_model_evaluation: >>>>>> Stage Evaluation Stage started <<<<<<]
[2023-10-25 23:32:43,691: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-10-25 23:32:43,693: INFO: common: yaml file: params.yaml loaded successfully]
[2023-10-25 23:32:43,693: INFO: common: Created directory at: artifacts]
[2023-10-25 23:33:00,962: INFO: common: Json file saved successfully at: scores.json]
[2023-10-25 23:33:00,963: INFO: stage_04_model_evaluation: >>>>>>> Stage Evaluation Stage completed <<<<<<<

x===================x]
[2023-10-26 00:04:46,701: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.250:8080]
[2023-10-26 00:04:46,702: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-26 00:05:10,919: INFO: _internal: 127.0.0.1 - - [26/Oct/2023 00:05:10] "GET / HTTP/1.1" 200 -]
[2023-10-26 00:05:58,650: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\rajat\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 40, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\rajat\onedrive\desktop\projects\kidney-disease-classification-mlflow\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    test_image = image.load_image(imagename, target_size= (224,224))
AttributeError: module 'keras.api._v2.keras.preprocessing.image' has no attribute 'load_image'
[2023-10-26 00:05:58,653: INFO: _internal: 127.0.0.1 - - [26/Oct/2023 00:05:58] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-10-26 00:08:06,191: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.250:8080]
[2023-10-26 00:08:06,191: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-10-26 00:08:14,138: INFO: _internal: 127.0.0.1 - - [26/Oct/2023 00:08:14] "GET / HTTP/1.1" 200 -]
[2023-10-26 00:08:21,837: INFO: _internal: 127.0.0.1 - - [26/Oct/2023 00:08:21] "POST /predict HTTP/1.1" 200 -]
[2023-10-26 00:08:47,942: INFO: _internal: 127.0.0.1 - - [26/Oct/2023 00:08:47] "POST /predict HTTP/1.1" 200 -]
[2023-10-26 00:09:00,605: INFO: _internal: 127.0.0.1 - - [26/Oct/2023 00:09:00] "POST /predict HTTP/1.1" 200 -]
